@echo off
echo This tool will delete all Oculus files except for the bare minimum required for Virtual Desktop to function.
echo The process is destructive, irreversible, and I offer no warranty or guarantees. You have been warned.
echo You'll likely require Virtual Desktop Streamer and SteamVR to run PCVR content after using this tool.
echo After 10 seconds, press any key to begin.
timeout 10 /nobreak
echo Last chance to back out!
pause
echo Beginning process...
@RD /S /Q "C:\Program Files\Oculus\CoreData"
@RD /S /Q "C:\Program Files\Oculus\Downloads"
@RD /S /Q "C:\Program Files\Oculus\Manifests"
@RD /S /Q "C:\Program Files\Oculus\Software"
@RD /S /Q "C:\Program Files\Oculus\Staging"
@RD /S /Q "C:\Program Files\Oculus\swap"
del /S /Q "C:\Program Files\Oculus\Oculus.ico"
del /S /Q "C:\Program Files\Oculus\OculusSetup.exe"
del /S /Q "C:\Program Files\Oculus\OVRLibraryService.log"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-worlds"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-avatar-editor"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-client"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-compat"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-dash"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-diagnostics"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-drivers"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-home"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-librarian"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-overlays"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-platform-runtime"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-redistributable-installer"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-touch-tutorial"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\Assets"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\client-plugins"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\mobileconfig"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\server-plugins"
@RD /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\translations"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\OculusAppFramework.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\OvrAvatarAssets.zip"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\RealtekWifi.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\RuntimeIPCServiceClient_32.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\RuntimeIPCServiceClient_64.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\symsrv.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\THIRD_PARTY_NOTICES.txt"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\xinput1_3.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\Compatibility.json"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\d3dcompiler_47.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\dbgcore.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\dbgeng.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\dbghelp.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\DbgModel.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\libEGL.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\libGLESv2.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\libovravatar.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRP2P32_1.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRP2P64_1.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRPlatform32.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRPlatform32_1.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRPlatform64.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRPlatform64_1.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\LibOVRRT32_1.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\oculus_openxr_32.json"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\oculus_openxr_64.json"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\oculus_p2p_32.dll"
del /S /Q "C:\Program Files\Oculus\Support\oculus-runtime\oculus_p2p_64.dll"
type nul > "C:\Program Files\Oculus\Support\oculus-runtime\OVRRedir.exe"
type nul > "C:\Program Files\Oculus\Support\oculus-runtime\OVRServer_x64.exe"
type nul > "C:\Program Files\Oculus\Support\oculus-runtime\OVRServiceLauncher.exe"
echo Complete.
pause